package io.github.jerryt92.j2agent.model.po.mgb;

import java.util.ArrayList;
import java.util.Arrays;

public class ApiKeyInfoPo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_key_info.api_key
     *
     * @mbg.generated
     */
    private String apiKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_key_info.api_key_owner
     *
     * @mbg.generated
     */
    private String apiKeyOwner;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_key_info.create_time
     *
     * @mbg.generated
     */
    private Long createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_key_info.expire_time
     *
     * @mbg.generated
     */
    private Long expireTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_key_info.api_key
     *
     * @return the value of api_key_info.api_key
     *
     * @mbg.generated
     */
    public String getApiKey() {
        return apiKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_key_info.api_key
     *
     * @param apiKey the value for api_key_info.api_key
     *
     * @mbg.generated
     */
    public void setApiKey(String apiKey) {
        this.apiKey = apiKey == null ? null : apiKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_key_info.api_key_owner
     *
     * @return the value of api_key_info.api_key_owner
     *
     * @mbg.generated
     */
    public String getApiKeyOwner() {
        return apiKeyOwner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_key_info.api_key_owner
     *
     * @param apiKeyOwner the value for api_key_info.api_key_owner
     *
     * @mbg.generated
     */
    public void setApiKeyOwner(String apiKeyOwner) {
        this.apiKeyOwner = apiKeyOwner == null ? null : apiKeyOwner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_key_info.create_time
     *
     * @return the value of api_key_info.create_time
     *
     * @mbg.generated
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_key_info.create_time
     *
     * @param createTime the value for api_key_info.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_key_info.expire_time
     *
     * @return the value of api_key_info.expire_time
     *
     * @mbg.generated
     */
    public Long getExpireTime() {
        return expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_key_info.expire_time
     *
     * @param expireTime the value for api_key_info.expire_time
     *
     * @mbg.generated
     */
    public void setExpireTime(Long expireTime) {
        this.expireTime = expireTime;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table api_key_info
     *
     * @mbg.generated
     */
    public enum Column {
        apiKey("api_key", "apiKey", "VARCHAR", false),
        apiKeyOwner("api_key_owner", "apiKeyOwner", "VARCHAR", false),
        createTime("create_time", "createTime", "BIGINT", false),
        expireTime("expire_time", "expireTime", "BIGINT", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table api_key_info
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "\"";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table api_key_info
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "\"";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table api_key_info
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table api_key_info
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table api_key_info
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table api_key_info
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table api_key_info
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table api_key_info
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table api_key_info
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table api_key_info
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table api_key_info
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table api_key_info
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table api_key_info
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table api_key_info
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table api_key_info
         *
         * @mbg.generated
         */
        public static Column[] all() {
            return Column.values();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table api_key_info
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table api_key_info
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}