package io.github.jerryt92.j2agent.model.po.mgb;

import java.util.ArrayList;
import java.util.Arrays;

public class ApiProviderConfigPo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_provider_config.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_provider_config.api_type
     *
     * @mbg.generated
     */
    private String apiType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_provider_config.config_name
     *
     * @mbg.generated
     */
    private String configName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_provider_config.provider_type
     *
     * @mbg.generated
     */
    private String providerType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_provider_config.config_json
     *
     * @mbg.generated
     */
    private String configJson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_provider_config.enabled
     *
     * @mbg.generated
     */
    private Short enabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_provider_config.is_current
     *
     * @mbg.generated
     */
    private Short isCurrent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_provider_config.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_provider_config.create_time
     *
     * @mbg.generated
     */
    private Long createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_provider_config.update_time
     *
     * @mbg.generated
     */
    private Long updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_provider_config.id
     *
     * @return the value of api_provider_config.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_provider_config.id
     *
     * @param id the value for api_provider_config.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_provider_config.api_type
     *
     * @return the value of api_provider_config.api_type
     *
     * @mbg.generated
     */
    public String getApiType() {
        return apiType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_provider_config.api_type
     *
     * @param apiType the value for api_provider_config.api_type
     *
     * @mbg.generated
     */
    public void setApiType(String apiType) {
        this.apiType = apiType == null ? null : apiType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_provider_config.config_name
     *
     * @return the value of api_provider_config.config_name
     *
     * @mbg.generated
     */
    public String getConfigName() {
        return configName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_provider_config.config_name
     *
     * @param configName the value for api_provider_config.config_name
     *
     * @mbg.generated
     */
    public void setConfigName(String configName) {
        this.configName = configName == null ? null : configName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_provider_config.provider_type
     *
     * @return the value of api_provider_config.provider_type
     *
     * @mbg.generated
     */
    public String getProviderType() {
        return providerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_provider_config.provider_type
     *
     * @param providerType the value for api_provider_config.provider_type
     *
     * @mbg.generated
     */
    public void setProviderType(String providerType) {
        this.providerType = providerType == null ? null : providerType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_provider_config.config_json
     *
     * @return the value of api_provider_config.config_json
     *
     * @mbg.generated
     */
    public String getConfigJson() {
        return configJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_provider_config.config_json
     *
     * @param configJson the value for api_provider_config.config_json
     *
     * @mbg.generated
     */
    public void setConfigJson(String configJson) {
        this.configJson = configJson == null ? null : configJson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_provider_config.enabled
     *
     * @return the value of api_provider_config.enabled
     *
     * @mbg.generated
     */
    public Short getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_provider_config.enabled
     *
     * @param enabled the value for api_provider_config.enabled
     *
     * @mbg.generated
     */
    public void setEnabled(Short enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_provider_config.is_current
     *
     * @return the value of api_provider_config.is_current
     *
     * @mbg.generated
     */
    public Short getIsCurrent() {
        return isCurrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_provider_config.is_current
     *
     * @param isCurrent the value for api_provider_config.is_current
     *
     * @mbg.generated
     */
    public void setIsCurrent(Short isCurrent) {
        this.isCurrent = isCurrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_provider_config.description
     *
     * @return the value of api_provider_config.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_provider_config.description
     *
     * @param description the value for api_provider_config.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_provider_config.create_time
     *
     * @return the value of api_provider_config.create_time
     *
     * @mbg.generated
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_provider_config.create_time
     *
     * @param createTime the value for api_provider_config.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_provider_config.update_time
     *
     * @return the value of api_provider_config.update_time
     *
     * @mbg.generated
     */
    public Long getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_provider_config.update_time
     *
     * @param updateTime the value for api_provider_config.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table api_provider_config
     *
     * @mbg.generated
     */
    public enum Column {
        id("id", "id", "BIGINT", false),
        apiType("api_type", "apiType", "VARCHAR", false),
        configName("config_name", "configName", "VARCHAR", false),
        providerType("provider_type", "providerType", "VARCHAR", false),
        configJson("config_json", "configJson", "VARCHAR", false),
        enabled("enabled", "enabled", "SMALLINT", false),
        isCurrent("is_current", "isCurrent", "SMALLINT", false),
        description("description", "description", "VARCHAR", false),
        createTime("create_time", "createTime", "BIGINT", false),
        updateTime("update_time", "updateTime", "BIGINT", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table api_provider_config
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "\"";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table api_provider_config
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "\"";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table api_provider_config
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table api_provider_config
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table api_provider_config
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table api_provider_config
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table api_provider_config
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table api_provider_config
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table api_provider_config
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table api_provider_config
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table api_provider_config
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table api_provider_config
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table api_provider_config
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table api_provider_config
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table api_provider_config
         *
         * @mbg.generated
         */
        public static Column[] all() {
            return Column.values();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table api_provider_config
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table api_provider_config
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}