package io.github.jerryt92.j2agent.model.po.mgb;

import java.util.ArrayList;
import java.util.Arrays;

public class ChatContextItem {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_context_item.message_id
     *
     * @mbg.generated
     */
    private String messageId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_context_item.context_id
     *
     * @mbg.generated
     */
    private String contextId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_context_item.agent_id
     *
     * @mbg.generated
     */
    private String agentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_context_item.message_index
     *
     * @mbg.generated
     */
    private Integer messageIndex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_context_item.chat_role
     *
     * @mbg.generated
     */
    private Integer chatRole;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_context_item.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_context_item.feedback
     *
     * @mbg.generated
     */
    private Integer feedback;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_context_item.rag_infos
     *
     * @mbg.generated
     */
    private String ragInfos;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_context_item.add_time
     *
     * @mbg.generated
     */
    private Long addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_context_item.meta_json
     *
     * @mbg.generated
     */
    private String metaJson;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_context_item.message_id
     *
     * @return the value of chat_context_item.message_id
     *
     * @mbg.generated
     */
    public String getMessageId() {
        return messageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_context_item.message_id
     *
     * @param messageId the value for chat_context_item.message_id
     *
     * @mbg.generated
     */
    public void setMessageId(String messageId) {
        this.messageId = messageId == null ? null : messageId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_context_item.context_id
     *
     * @return the value of chat_context_item.context_id
     *
     * @mbg.generated
     */
    public String getContextId() {
        return contextId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_context_item.context_id
     *
     * @param contextId the value for chat_context_item.context_id
     *
     * @mbg.generated
     */
    public void setContextId(String contextId) {
        this.contextId = contextId == null ? null : contextId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_context_item.agent_id
     *
     * @return the value of chat_context_item.agent_id
     *
     * @mbg.generated
     */
    public String getAgentId() {
        return agentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_context_item.agent_id
     *
     * @param agentId the value for chat_context_item.agent_id
     *
     * @mbg.generated
     */
    public void setAgentId(String agentId) {
        this.agentId = agentId == null ? null : agentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_context_item.message_index
     *
     * @return the value of chat_context_item.message_index
     *
     * @mbg.generated
     */
    public Integer getMessageIndex() {
        return messageIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_context_item.message_index
     *
     * @param messageIndex the value for chat_context_item.message_index
     *
     * @mbg.generated
     */
    public void setMessageIndex(Integer messageIndex) {
        this.messageIndex = messageIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_context_item.chat_role
     *
     * @return the value of chat_context_item.chat_role
     *
     * @mbg.generated
     */
    public Integer getChatRole() {
        return chatRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_context_item.chat_role
     *
     * @param chatRole the value for chat_context_item.chat_role
     *
     * @mbg.generated
     */
    public void setChatRole(Integer chatRole) {
        this.chatRole = chatRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_context_item.content
     *
     * @return the value of chat_context_item.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_context_item.content
     *
     * @param content the value for chat_context_item.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_context_item.feedback
     *
     * @return the value of chat_context_item.feedback
     *
     * @mbg.generated
     */
    public Integer getFeedback() {
        return feedback;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_context_item.feedback
     *
     * @param feedback the value for chat_context_item.feedback
     *
     * @mbg.generated
     */
    public void setFeedback(Integer feedback) {
        this.feedback = feedback;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_context_item.rag_infos
     *
     * @return the value of chat_context_item.rag_infos
     *
     * @mbg.generated
     */
    public String getRagInfos() {
        return ragInfos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_context_item.rag_infos
     *
     * @param ragInfos the value for chat_context_item.rag_infos
     *
     * @mbg.generated
     */
    public void setRagInfos(String ragInfos) {
        this.ragInfos = ragInfos == null ? null : ragInfos.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_context_item.add_time
     *
     * @return the value of chat_context_item.add_time
     *
     * @mbg.generated
     */
    public Long getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_context_item.add_time
     *
     * @param addTime the value for chat_context_item.add_time
     *
     * @mbg.generated
     */
    public void setAddTime(Long addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_context_item.meta_json
     *
     * @return the value of chat_context_item.meta_json
     *
     * @mbg.generated
     */
    public String getMetaJson() {
        return metaJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_context_item.meta_json
     *
     * @param metaJson the value for chat_context_item.meta_json
     *
     * @mbg.generated
     */
    public void setMetaJson(String metaJson) {
        this.metaJson = metaJson == null ? null : metaJson.trim();
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table chat_context_item
     *
     * @mbg.generated
     */
    public enum Column {
        messageId("message_id", "messageId", "CHAR", false),
        contextId("context_id", "contextId", "VARCHAR", false),
        agentId("agent_id", "agentId", "VARCHAR", false),
        messageIndex("message_index", "messageIndex", "INTEGER", false),
        chatRole("chat_role", "chatRole", "INTEGER", false),
        content("content", "content", "VARCHAR", false),
        feedback("feedback", "feedback", "INTEGER", false),
        ragInfos("rag_infos", "ragInfos", "VARCHAR", false),
        addTime("add_time", "addTime", "BIGINT", false),
        metaJson("meta_json", "metaJson", "VARCHAR", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table chat_context_item
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "\"";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table chat_context_item
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "\"";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table chat_context_item
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table chat_context_item
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table chat_context_item
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table chat_context_item
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table chat_context_item
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table chat_context_item
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table chat_context_item
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table chat_context_item
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table chat_context_item
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table chat_context_item
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table chat_context_item
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table chat_context_item
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table chat_context_item
         *
         * @mbg.generated
         */
        public static Column[] all() {
            return Column.values();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table chat_context_item
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table chat_context_item
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}