package io.github.jerryt92.j2agent.model.po.mgb;

import java.util.ArrayList;
import java.util.List;

public class ChatContextItemExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table chat_context_item
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table chat_context_item
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table chat_context_item
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    protected Integer limit;

    protected Integer offset;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_context_item
     *
     * @mbg.generated
     */
    public ChatContextItemExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_context_item
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_context_item
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_context_item
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_context_item
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_context_item
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_context_item
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_context_item
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_context_item
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_context_item
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_context_item
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    public void setLimit(Integer limit) {
        this.limit = limit;
    }

    public Integer getLimit() {
        return this.limit;
    }

    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    public Integer getOffset() {
        return this.offset;
    }

    public BoundBuilder boundBuilder() {
        return new BoundBuilder();
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table chat_context_item
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMessageIdIsNull() {
            addCriterion("message_id is null");
            return (Criteria) this;
        }

        public Criteria andMessageIdIsNotNull() {
            addCriterion("message_id is not null");
            return (Criteria) this;
        }

        public Criteria andMessageIdEqualTo(String value) {
            addCriterion("message_id =", value, "messageId");
            return (Criteria) this;
        }

        public Criteria andMessageIdNotEqualTo(String value) {
            addCriterion("message_id <>", value, "messageId");
            return (Criteria) this;
        }

        public Criteria andMessageIdGreaterThan(String value) {
            addCriterion("message_id >", value, "messageId");
            return (Criteria) this;
        }

        public Criteria andMessageIdGreaterThanOrEqualTo(String value) {
            addCriterion("message_id >=", value, "messageId");
            return (Criteria) this;
        }

        public Criteria andMessageIdLessThan(String value) {
            addCriterion("message_id <", value, "messageId");
            return (Criteria) this;
        }

        public Criteria andMessageIdLessThanOrEqualTo(String value) {
            addCriterion("message_id <=", value, "messageId");
            return (Criteria) this;
        }

        public Criteria andMessageIdLike(String value) {
            addCriterion("message_id like", value, "messageId");
            return (Criteria) this;
        }

        public Criteria andMessageIdNotLike(String value) {
            addCriterion("message_id not like", value, "messageId");
            return (Criteria) this;
        }

        public Criteria andMessageIdIn(List<String> values) {
            addCriterion("message_id in", values, "messageId");
            return (Criteria) this;
        }

        public Criteria andMessageIdNotIn(List<String> values) {
            addCriterion("message_id not in", values, "messageId");
            return (Criteria) this;
        }

        public Criteria andMessageIdBetween(String value1, String value2) {
            addCriterion("message_id between", value1, value2, "messageId");
            return (Criteria) this;
        }

        public Criteria andMessageIdNotBetween(String value1, String value2) {
            addCriterion("message_id not between", value1, value2, "messageId");
            return (Criteria) this;
        }

        public Criteria andContextIdIsNull() {
            addCriterion("context_id is null");
            return (Criteria) this;
        }

        public Criteria andContextIdIsNotNull() {
            addCriterion("context_id is not null");
            return (Criteria) this;
        }

        public Criteria andContextIdEqualTo(String value) {
            addCriterion("context_id =", value, "contextId");
            return (Criteria) this;
        }

        public Criteria andContextIdNotEqualTo(String value) {
            addCriterion("context_id <>", value, "contextId");
            return (Criteria) this;
        }

        public Criteria andContextIdGreaterThan(String value) {
            addCriterion("context_id >", value, "contextId");
            return (Criteria) this;
        }

        public Criteria andContextIdGreaterThanOrEqualTo(String value) {
            addCriterion("context_id >=", value, "contextId");
            return (Criteria) this;
        }

        public Criteria andContextIdLessThan(String value) {
            addCriterion("context_id <", value, "contextId");
            return (Criteria) this;
        }

        public Criteria andContextIdLessThanOrEqualTo(String value) {
            addCriterion("context_id <=", value, "contextId");
            return (Criteria) this;
        }

        public Criteria andContextIdLike(String value) {
            addCriterion("context_id like", value, "contextId");
            return (Criteria) this;
        }

        public Criteria andContextIdNotLike(String value) {
            addCriterion("context_id not like", value, "contextId");
            return (Criteria) this;
        }

        public Criteria andContextIdIn(List<String> values) {
            addCriterion("context_id in", values, "contextId");
            return (Criteria) this;
        }

        public Criteria andContextIdNotIn(List<String> values) {
            addCriterion("context_id not in", values, "contextId");
            return (Criteria) this;
        }

        public Criteria andContextIdBetween(String value1, String value2) {
            addCriterion("context_id between", value1, value2, "contextId");
            return (Criteria) this;
        }

        public Criteria andContextIdNotBetween(String value1, String value2) {
            addCriterion("context_id not between", value1, value2, "contextId");
            return (Criteria) this;
        }

        public Criteria andAgentIdIsNull() {
            addCriterion("agent_id is null");
            return (Criteria) this;
        }

        public Criteria andAgentIdIsNotNull() {
            addCriterion("agent_id is not null");
            return (Criteria) this;
        }

        public Criteria andAgentIdEqualTo(String value) {
            addCriterion("agent_id =", value, "agentId");
            return (Criteria) this;
        }

        public Criteria andAgentIdNotEqualTo(String value) {
            addCriterion("agent_id <>", value, "agentId");
            return (Criteria) this;
        }

        public Criteria andAgentIdGreaterThan(String value) {
            addCriterion("agent_id >", value, "agentId");
            return (Criteria) this;
        }

        public Criteria andAgentIdGreaterThanOrEqualTo(String value) {
            addCriterion("agent_id >=", value, "agentId");
            return (Criteria) this;
        }

        public Criteria andAgentIdLessThan(String value) {
            addCriterion("agent_id <", value, "agentId");
            return (Criteria) this;
        }

        public Criteria andAgentIdLessThanOrEqualTo(String value) {
            addCriterion("agent_id <=", value, "agentId");
            return (Criteria) this;
        }

        public Criteria andAgentIdLike(String value) {
            addCriterion("agent_id like", value, "agentId");
            return (Criteria) this;
        }

        public Criteria andAgentIdNotLike(String value) {
            addCriterion("agent_id not like", value, "agentId");
            return (Criteria) this;
        }

        public Criteria andAgentIdIn(List<String> values) {
            addCriterion("agent_id in", values, "agentId");
            return (Criteria) this;
        }

        public Criteria andAgentIdNotIn(List<String> values) {
            addCriterion("agent_id not in", values, "agentId");
            return (Criteria) this;
        }

        public Criteria andAgentIdBetween(String value1, String value2) {
            addCriterion("agent_id between", value1, value2, "agentId");
            return (Criteria) this;
        }

        public Criteria andAgentIdNotBetween(String value1, String value2) {
            addCriterion("agent_id not between", value1, value2, "agentId");
            return (Criteria) this;
        }

        public Criteria andMessageIndexIsNull() {
            addCriterion("message_index is null");
            return (Criteria) this;
        }

        public Criteria andMessageIndexIsNotNull() {
            addCriterion("message_index is not null");
            return (Criteria) this;
        }

        public Criteria andMessageIndexEqualTo(Integer value) {
            addCriterion("message_index =", value, "messageIndex");
            return (Criteria) this;
        }

        public Criteria andMessageIndexNotEqualTo(Integer value) {
            addCriterion("message_index <>", value, "messageIndex");
            return (Criteria) this;
        }

        public Criteria andMessageIndexGreaterThan(Integer value) {
            addCriterion("message_index >", value, "messageIndex");
            return (Criteria) this;
        }

        public Criteria andMessageIndexGreaterThanOrEqualTo(Integer value) {
            addCriterion("message_index >=", value, "messageIndex");
            return (Criteria) this;
        }

        public Criteria andMessageIndexLessThan(Integer value) {
            addCriterion("message_index <", value, "messageIndex");
            return (Criteria) this;
        }

        public Criteria andMessageIndexLessThanOrEqualTo(Integer value) {
            addCriterion("message_index <=", value, "messageIndex");
            return (Criteria) this;
        }

        public Criteria andMessageIndexIn(List<Integer> values) {
            addCriterion("message_index in", values, "messageIndex");
            return (Criteria) this;
        }

        public Criteria andMessageIndexNotIn(List<Integer> values) {
            addCriterion("message_index not in", values, "messageIndex");
            return (Criteria) this;
        }

        public Criteria andMessageIndexBetween(Integer value1, Integer value2) {
            addCriterion("message_index between", value1, value2, "messageIndex");
            return (Criteria) this;
        }

        public Criteria andMessageIndexNotBetween(Integer value1, Integer value2) {
            addCriterion("message_index not between", value1, value2, "messageIndex");
            return (Criteria) this;
        }

        public Criteria andChatRoleIsNull() {
            addCriterion("chat_role is null");
            return (Criteria) this;
        }

        public Criteria andChatRoleIsNotNull() {
            addCriterion("chat_role is not null");
            return (Criteria) this;
        }

        public Criteria andChatRoleEqualTo(Integer value) {
            addCriterion("chat_role =", value, "chatRole");
            return (Criteria) this;
        }

        public Criteria andChatRoleNotEqualTo(Integer value) {
            addCriterion("chat_role <>", value, "chatRole");
            return (Criteria) this;
        }

        public Criteria andChatRoleGreaterThan(Integer value) {
            addCriterion("chat_role >", value, "chatRole");
            return (Criteria) this;
        }

        public Criteria andChatRoleGreaterThanOrEqualTo(Integer value) {
            addCriterion("chat_role >=", value, "chatRole");
            return (Criteria) this;
        }

        public Criteria andChatRoleLessThan(Integer value) {
            addCriterion("chat_role <", value, "chatRole");
            return (Criteria) this;
        }

        public Criteria andChatRoleLessThanOrEqualTo(Integer value) {
            addCriterion("chat_role <=", value, "chatRole");
            return (Criteria) this;
        }

        public Criteria andChatRoleIn(List<Integer> values) {
            addCriterion("chat_role in", values, "chatRole");
            return (Criteria) this;
        }

        public Criteria andChatRoleNotIn(List<Integer> values) {
            addCriterion("chat_role not in", values, "chatRole");
            return (Criteria) this;
        }

        public Criteria andChatRoleBetween(Integer value1, Integer value2) {
            addCriterion("chat_role between", value1, value2, "chatRole");
            return (Criteria) this;
        }

        public Criteria andChatRoleNotBetween(Integer value1, Integer value2) {
            addCriterion("chat_role not between", value1, value2, "chatRole");
            return (Criteria) this;
        }

        public Criteria andContentIsNull() {
            addCriterion("content is null");
            return (Criteria) this;
        }

        public Criteria andContentIsNotNull() {
            addCriterion("content is not null");
            return (Criteria) this;
        }

        public Criteria andContentEqualTo(String value) {
            addCriterion("content =", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotEqualTo(String value) {
            addCriterion("content <>", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentGreaterThan(String value) {
            addCriterion("content >", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentGreaterThanOrEqualTo(String value) {
            addCriterion("content >=", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLessThan(String value) {
            addCriterion("content <", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLessThanOrEqualTo(String value) {
            addCriterion("content <=", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLike(String value) {
            addCriterion("content like", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotLike(String value) {
            addCriterion("content not like", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentIn(List<String> values) {
            addCriterion("content in", values, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotIn(List<String> values) {
            addCriterion("content not in", values, "content");
            return (Criteria) this;
        }

        public Criteria andContentBetween(String value1, String value2) {
            addCriterion("content between", value1, value2, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotBetween(String value1, String value2) {
            addCriterion("content not between", value1, value2, "content");
            return (Criteria) this;
        }

        public Criteria andFeedbackIsNull() {
            addCriterion("feedback is null");
            return (Criteria) this;
        }

        public Criteria andFeedbackIsNotNull() {
            addCriterion("feedback is not null");
            return (Criteria) this;
        }

        public Criteria andFeedbackEqualTo(Integer value) {
            addCriterion("feedback =", value, "feedback");
            return (Criteria) this;
        }

        public Criteria andFeedbackNotEqualTo(Integer value) {
            addCriterion("feedback <>", value, "feedback");
            return (Criteria) this;
        }

        public Criteria andFeedbackGreaterThan(Integer value) {
            addCriterion("feedback >", value, "feedback");
            return (Criteria) this;
        }

        public Criteria andFeedbackGreaterThanOrEqualTo(Integer value) {
            addCriterion("feedback >=", value, "feedback");
            return (Criteria) this;
        }

        public Criteria andFeedbackLessThan(Integer value) {
            addCriterion("feedback <", value, "feedback");
            return (Criteria) this;
        }

        public Criteria andFeedbackLessThanOrEqualTo(Integer value) {
            addCriterion("feedback <=", value, "feedback");
            return (Criteria) this;
        }

        public Criteria andFeedbackIn(List<Integer> values) {
            addCriterion("feedback in", values, "feedback");
            return (Criteria) this;
        }

        public Criteria andFeedbackNotIn(List<Integer> values) {
            addCriterion("feedback not in", values, "feedback");
            return (Criteria) this;
        }

        public Criteria andFeedbackBetween(Integer value1, Integer value2) {
            addCriterion("feedback between", value1, value2, "feedback");
            return (Criteria) this;
        }

        public Criteria andFeedbackNotBetween(Integer value1, Integer value2) {
            addCriterion("feedback not between", value1, value2, "feedback");
            return (Criteria) this;
        }

        public Criteria andRagInfosIsNull() {
            addCriterion("rag_infos is null");
            return (Criteria) this;
        }

        public Criteria andRagInfosIsNotNull() {
            addCriterion("rag_infos is not null");
            return (Criteria) this;
        }

        public Criteria andRagInfosEqualTo(String value) {
            addCriterion("rag_infos =", value, "ragInfos");
            return (Criteria) this;
        }

        public Criteria andRagInfosNotEqualTo(String value) {
            addCriterion("rag_infos <>", value, "ragInfos");
            return (Criteria) this;
        }

        public Criteria andRagInfosGreaterThan(String value) {
            addCriterion("rag_infos >", value, "ragInfos");
            return (Criteria) this;
        }

        public Criteria andRagInfosGreaterThanOrEqualTo(String value) {
            addCriterion("rag_infos >=", value, "ragInfos");
            return (Criteria) this;
        }

        public Criteria andRagInfosLessThan(String value) {
            addCriterion("rag_infos <", value, "ragInfos");
            return (Criteria) this;
        }

        public Criteria andRagInfosLessThanOrEqualTo(String value) {
            addCriterion("rag_infos <=", value, "ragInfos");
            return (Criteria) this;
        }

        public Criteria andRagInfosLike(String value) {
            addCriterion("rag_infos like", value, "ragInfos");
            return (Criteria) this;
        }

        public Criteria andRagInfosNotLike(String value) {
            addCriterion("rag_infos not like", value, "ragInfos");
            return (Criteria) this;
        }

        public Criteria andRagInfosIn(List<String> values) {
            addCriterion("rag_infos in", values, "ragInfos");
            return (Criteria) this;
        }

        public Criteria andRagInfosNotIn(List<String> values) {
            addCriterion("rag_infos not in", values, "ragInfos");
            return (Criteria) this;
        }

        public Criteria andRagInfosBetween(String value1, String value2) {
            addCriterion("rag_infos between", value1, value2, "ragInfos");
            return (Criteria) this;
        }

        public Criteria andRagInfosNotBetween(String value1, String value2) {
            addCriterion("rag_infos not between", value1, value2, "ragInfos");
            return (Criteria) this;
        }

        public Criteria andAddTimeIsNull() {
            addCriterion("add_time is null");
            return (Criteria) this;
        }

        public Criteria andAddTimeIsNotNull() {
            addCriterion("add_time is not null");
            return (Criteria) this;
        }

        public Criteria andAddTimeEqualTo(Long value) {
            addCriterion("add_time =", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotEqualTo(Long value) {
            addCriterion("add_time <>", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeGreaterThan(Long value) {
            addCriterion("add_time >", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeGreaterThanOrEqualTo(Long value) {
            addCriterion("add_time >=", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeLessThan(Long value) {
            addCriterion("add_time <", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeLessThanOrEqualTo(Long value) {
            addCriterion("add_time <=", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeIn(List<Long> values) {
            addCriterion("add_time in", values, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotIn(List<Long> values) {
            addCriterion("add_time not in", values, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeBetween(Long value1, Long value2) {
            addCriterion("add_time between", value1, value2, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotBetween(Long value1, Long value2) {
            addCriterion("add_time not between", value1, value2, "addTime");
            return (Criteria) this;
        }

        public Criteria andMetaJsonIsNull() {
            addCriterion("meta_json is null");
            return (Criteria) this;
        }

        public Criteria andMetaJsonIsNotNull() {
            addCriterion("meta_json is not null");
            return (Criteria) this;
        }

        public Criteria andMetaJsonEqualTo(String value) {
            addCriterion("meta_json =", value, "metaJson");
            return (Criteria) this;
        }

        public Criteria andMetaJsonNotEqualTo(String value) {
            addCriterion("meta_json <>", value, "metaJson");
            return (Criteria) this;
        }

        public Criteria andMetaJsonGreaterThan(String value) {
            addCriterion("meta_json >", value, "metaJson");
            return (Criteria) this;
        }

        public Criteria andMetaJsonGreaterThanOrEqualTo(String value) {
            addCriterion("meta_json >=", value, "metaJson");
            return (Criteria) this;
        }

        public Criteria andMetaJsonLessThan(String value) {
            addCriterion("meta_json <", value, "metaJson");
            return (Criteria) this;
        }

        public Criteria andMetaJsonLessThanOrEqualTo(String value) {
            addCriterion("meta_json <=", value, "metaJson");
            return (Criteria) this;
        }

        public Criteria andMetaJsonLike(String value) {
            addCriterion("meta_json like", value, "metaJson");
            return (Criteria) this;
        }

        public Criteria andMetaJsonNotLike(String value) {
            addCriterion("meta_json not like", value, "metaJson");
            return (Criteria) this;
        }

        public Criteria andMetaJsonIn(List<String> values) {
            addCriterion("meta_json in", values, "metaJson");
            return (Criteria) this;
        }

        public Criteria andMetaJsonNotIn(List<String> values) {
            addCriterion("meta_json not in", values, "metaJson");
            return (Criteria) this;
        }

        public Criteria andMetaJsonBetween(String value1, String value2) {
            addCriterion("meta_json between", value1, value2, "metaJson");
            return (Criteria) this;
        }

        public Criteria andMetaJsonNotBetween(String value1, String value2) {
            addCriterion("meta_json not between", value1, value2, "metaJson");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table chat_context_item
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table chat_context_item
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }

    public class BoundBuilder {
        protected Integer limit;

        protected Integer offset;

        public Integer limit() {
            return this.limit;
        }

        public BoundBuilder limit(Integer limit) {
            this.limit = limit;
            return this;
        }

        public Integer offset() {
            return this.offset;
        }

        public BoundBuilder offset(Integer offset) {
            this.offset = offset;
            return this;
        }

        public ChatContextItemExample build() {
            ChatContextItemExample.this.limit = limit;
            ChatContextItemExample.this.offset = offset;
            return ChatContextItemExample.this;
        }
    }
}