package io.github.jerryt92.j2agent.mapper.mgb;

import io.github.jerryt92.j2agent.model.po.mgb.ApiKeyInfoPo;
import io.github.jerryt92.j2agent.model.po.mgb.ApiKeyInfoPoExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface ApiKeyInfoPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_key_info
     *
     * @mbg.generated
     */
    long countByExample(ApiKeyInfoPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_key_info
     *
     * @mbg.generated
     */
    int deleteByExample(ApiKeyInfoPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_key_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String apiKey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_key_info
     *
     * @mbg.generated
     */
    int insert(ApiKeyInfoPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_key_info
     *
     * @mbg.generated
     */
    int insertSelective(ApiKeyInfoPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_key_info
     *
     * @mbg.generated
     */
    List<ApiKeyInfoPo> selectByExample(ApiKeyInfoPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_key_info
     *
     * @mbg.generated
     */
    ApiKeyInfoPo selectByPrimaryKey(String apiKey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_key_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ApiKeyInfoPo record, @Param("example") ApiKeyInfoPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_key_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ApiKeyInfoPo record, @Param("example") ApiKeyInfoPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_key_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ApiKeyInfoPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_key_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ApiKeyInfoPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_key_info
     *
     * @mbg.generated
     */
    int batchInsert(@Param("list") List<ApiKeyInfoPo> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_key_info
     *
     * @mbg.generated
     */
    int batchInsertSelective(@Param("list") List<ApiKeyInfoPo> list, @Param("selective") ApiKeyInfoPo.Column ... selective);
}