package io.github.jerryt92.j2agent.mapper.mgb;

import io.github.jerryt92.j2agent.model.po.mgb.ApiProviderConfigPo;
import io.github.jerryt92.j2agent.model.po.mgb.ApiProviderConfigPoExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface ApiProviderConfigPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_provider_config
     *
     * @mbg.generated
     */
    long countByExample(ApiProviderConfigPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_provider_config
     *
     * @mbg.generated
     */
    int deleteByExample(ApiProviderConfigPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_provider_config
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_provider_config
     *
     * @mbg.generated
     */
    int insert(ApiProviderConfigPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_provider_config
     *
     * @mbg.generated
     */
    int insertSelective(ApiProviderConfigPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_provider_config
     *
     * @mbg.generated
     */
    List<ApiProviderConfigPo> selectByExample(ApiProviderConfigPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_provider_config
     *
     * @mbg.generated
     */
    ApiProviderConfigPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_provider_config
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ApiProviderConfigPo record, @Param("example") ApiProviderConfigPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_provider_config
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ApiProviderConfigPo record, @Param("example") ApiProviderConfigPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_provider_config
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ApiProviderConfigPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_provider_config
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ApiProviderConfigPo record);
}