package io.github.jerryt92.j2agent.mapper.mgb;

import io.github.jerryt92.j2agent.model.po.mgb.ChatContextItem;
import io.github.jerryt92.j2agent.model.po.mgb.ChatContextItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface ChatContextItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_context_item
     *
     * @mbg.generated
     */
    long countByExample(ChatContextItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_context_item
     *
     * @mbg.generated
     */
    int deleteByExample(ChatContextItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_context_item
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String messageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_context_item
     *
     * @mbg.generated
     */
    int insert(ChatContextItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_context_item
     *
     * @mbg.generated
     */
    int insertSelective(ChatContextItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_context_item
     *
     * @mbg.generated
     */
    List<ChatContextItem> selectByExample(ChatContextItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_context_item
     *
     * @mbg.generated
     */
    ChatContextItem selectByPrimaryKey(String messageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_context_item
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ChatContextItem record, @Param("example") ChatContextItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_context_item
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ChatContextItem record, @Param("example") ChatContextItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_context_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ChatContextItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_context_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ChatContextItem record);
}