package io.github.jerryt92.j2agent.mapper.mgb;

import io.github.jerryt92.j2agent.model.po.mgb.ContextRecordItemPo;
import io.github.jerryt92.j2agent.model.po.mgb.ContextRecordItemPoExample;
import io.github.jerryt92.j2agent.model.po.mgb.ContextRecordItemPoWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface ContextRecordItemPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table context_record_item
     *
     * @mbg.generated
     */
    long countByExample(ContextRecordItemPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table context_record_item
     *
     * @mbg.generated
     */
    int deleteByExample(ContextRecordItemPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table context_record_item
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table context_record_item
     *
     * @mbg.generated
     */
    int insert(ContextRecordItemPoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table context_record_item
     *
     * @mbg.generated
     */
    int insertSelective(ContextRecordItemPoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table context_record_item
     *
     * @mbg.generated
     */
    List<ContextRecordItemPoWithBLOBs> selectByExampleWithBLOBs(ContextRecordItemPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table context_record_item
     *
     * @mbg.generated
     */
    List<ContextRecordItemPo> selectByExample(ContextRecordItemPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table context_record_item
     *
     * @mbg.generated
     */
    ContextRecordItemPoWithBLOBs selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table context_record_item
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ContextRecordItemPoWithBLOBs record, @Param("example") ContextRecordItemPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table context_record_item
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") ContextRecordItemPoWithBLOBs record, @Param("example") ContextRecordItemPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table context_record_item
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ContextRecordItemPo record, @Param("example") ContextRecordItemPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table context_record_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ContextRecordItemPoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table context_record_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(ContextRecordItemPoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table context_record_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ContextRecordItemPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table context_record_item
     *
     * @mbg.generated
     */
    int batchInsert(@Param("list") List<ContextRecordItemPoWithBLOBs> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table context_record_item
     *
     * @mbg.generated
     */
    int batchInsertSelective(@Param("list") List<ContextRecordItemPoWithBLOBs> list, @Param("selective") ContextRecordItemPoWithBLOBs.Column ... selective);
}