package io.github.jerryt92.j2agent.mapper.mgb;

import io.github.jerryt92.j2agent.model.po.mgb.ContextRecordPo;
import io.github.jerryt92.j2agent.model.po.mgb.ContextRecordPoExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface ContextRecordPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table context_record
     *
     * @mbg.generated
     */
    long countByExample(ContextRecordPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table context_record
     *
     * @mbg.generated
     */
    int deleteByExample(ContextRecordPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table context_record
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String contextId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table context_record
     *
     * @mbg.generated
     */
    int insert(ContextRecordPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table context_record
     *
     * @mbg.generated
     */
    int insertSelective(ContextRecordPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table context_record
     *
     * @mbg.generated
     */
    List<ContextRecordPo> selectByExample(ContextRecordPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table context_record
     *
     * @mbg.generated
     */
    ContextRecordPo selectByPrimaryKey(String contextId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table context_record
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ContextRecordPo record, @Param("example") ContextRecordPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table context_record
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ContextRecordPo record, @Param("example") ContextRecordPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table context_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ContextRecordPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table context_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ContextRecordPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table context_record
     *
     * @mbg.generated
     */
    int batchInsert(@Param("list") List<ContextRecordPo> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table context_record
     *
     * @mbg.generated
     */
    int batchInsertSelective(@Param("list") List<ContextRecordPo> list, @Param("selective") ContextRecordPo.Column ... selective);
}