#driverLocation=D:/workspace/INC-Platform/platsvc-topology/platsvc-topology-server/target/libs/mysql-connector-j-8.0.31.jar
driverClassName=com.mysql.cj.jdbc.Driver
url=jdbc:mysql://127.0.0.1:30136/j2agent?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&autoReconnect=true&autoReconnectForPools=true&useLocalSessionState=true&allowMultiQueries=true&allowPublicKeyRetrieval=true&serverTimezone=UTC
username=root
password=Raisecom3##