package io.github.jerryt92.j2agent.constants;

/**
 * API 错误码（对应 resources/j2agent-i18n*.properties 中的 {code}.msg）。
 */
public interface ErrorConstants {

    String FILE_UPLOAD_SIZE_LIMIT = "FILE_UPLOAD_SIZE_LIMIT";

    String REGISTER_DISABLED = "REGISTER_DISABLED";
    String REGISTER_EMAIL_REQUIRED = "REGISTER_EMAIL_REQUIRED";
    String REGISTER_CODE_REQUIRED = "REGISTER_CODE_REQUIRED";
    String REGISTER_CODE_INVALID = "REGISTER_CODE_INVALID";
    String REGISTER_RATE_LIMIT = "REGISTER_RATE_LIMIT";
    String REGISTER_FIELDS_REQUIRED = "REGISTER_FIELDS_REQUIRED";
    String REGISTER_USERNAME_EXISTS = "REGISTER_USERNAME_EXISTS";
    String REGISTER_EMAIL_EXISTS = "REGISTER_EMAIL_EXISTS";
    String REGISTER_EMAIL_NOT_ALLOWED = "REGISTER_EMAIL_NOT_ALLOWED";
    String COMMON_REDIS_UNAVAILABLE = "COMMON_REDIS_UNAVAILABLE";
    /** 未预期系统错误，message 占位符为 traceId。 */
    String COMMON_INTERNAL_ERROR = "COMMON_INTERNAL_ERROR";
    String REGISTER_SMTP_NOT_CONFIGURED = "REGISTER_SMTP_NOT_CONFIGURED";
    String REGISTER_SMTP_INVALID = "REGISTER_SMTP_INVALID";
    String REGISTER_SMTP_PASSWORD_REQUIRED = "REGISTER_SMTP_PASSWORD_REQUIRED";
    String REGISTER_SEND_FAILED = "REGISTER_SEND_FAILED";

    String RESET_PASSWORD_EMAIL_REQUIRED = "RESET_PASSWORD_EMAIL_REQUIRED";
    String RESET_PASSWORD_CODE_REQUIRED = "RESET_PASSWORD_CODE_REQUIRED";
    String RESET_PASSWORD_CODE_INVALID = "RESET_PASSWORD_CODE_INVALID";
    String RESET_PASSWORD_RATE_LIMIT = "RESET_PASSWORD_RATE_LIMIT";
    String RESET_PASSWORD_FIELDS_REQUIRED = "RESET_PASSWORD_FIELDS_REQUIRED";
    String RESET_PASSWORD_SEND_FAILED = "RESET_PASSWORD_SEND_FAILED";

    /** 对话流式进行中，禁止删除历史上下文。 */
    String CHAT_CONTEXT_IN_PROGRESS = "CHAT_CONTEXT_IN_PROGRESS";
}
